const express = require('express');
const PDFDocument = require('pdfkit');
const pool = require('../db/index');
const router = express.Router();

router.get('/report/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query('SELECT * FROM reports WHERE id = $1', [id]);
    if (result.rows.length === 0) return res.status(404).json({ error: 'Report not found' });
    
    const report = result.rows[0];
    const doc = new PDFDocument();
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=KenyaWatch_Report_${id}.pdf`);
    
    doc.pipe(res);
    doc.fontSize(20).text('KenyaWatch AI - Fraud Alert Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Report ID: ${report.id}`);
    doc.text(`County: ${report.county}`);
    doc.text(`Project: ${report.project_name}`);
    doc.text(`Date Submitted: ${report.created_at.toDateString()}`);
    doc.moveDown();
    doc.text('Description:', { underline: true });
    doc.text(report.description);
    doc.moveDown();
    doc.fontSize(10).text('Generated by KenyaWatch AI System', { align: 'center' });
    
    doc.end();
  } catch (error) {
    console.error('PDF Export error:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

module.exports = router;
